---
version: 2.1

orbs:
  op: twdps/onepassword@2.0.6
  do: twdps/pipeline-events@3.2.2

globals:
  - &context empc-lab
  - &executor-image twdps/circleci-python-builder:3.0.2

on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

on-tag-main: &on-tag-main
  branches:
    ignore: /.*/
  tags:
    only: /.*/

commands:

  set-environment:
    parameters:
      tenant:
        description: set tenant ENV
        type: string
    steps:
      - op/env:
          env-file: op.<< parameters.tenant >>.env

jobs:

  configure-auth0-tenant:
    description: configure auth0 tenant
    docker:
      - image: *executor-image
    parameters:
      tenant:
        description: auth0 tenant to configure
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - set-environment:
          tenant: << parameters.tenant >>
      - run:
          name: install requirements
          command: pip install -r requirements.txt
      - run:
          name: lint invoke tasks
          command: pylint tasks
      - run:
          name: configure Auth0 tenant
          command: inv idp.install
      - run:
          name: write tenant Application credentials to secrets store
          command: bash scripts/write_client_credentials.sh

workflows:

  development tenant build:
    jobs:
      - configure-auth0-tenant:
          name: configure dev-pskctl tenant
          context: *context
          tenant: dev-pskctl
          filters: *on-push-main

  production tenant configuration:
    jobs:
      - configure-auth0-tenant:
          name: configure pskctl tenant
          context: *context
          tenant: pskctl
          filters: *on-tag-main

      - do/release:
          name: generate release notes
          context: *context
          on-tag: true
          before-release:
            - set-environment:
                tenant: pskctl
          requires:
            - configure pskctl tenant
          filters: *on-tag-main

      - do/slack:
          name: post lab-events
          context: *context
          channel: lab-events
          message: pskctl Auth0 tenant application release
          include-link: true
          include-tag: true
          before-message:
            - set-environment:
                tenant: pskctl
          requires:
            - configure pskctl tenant
          filters: *on-tag-main
